FROM node:8

COPY dist /universal/dist
COPY node_modules /universal/node_modules
COPY package.json /universal/package.json

EXPOSE 3200

ENTRYPOINT ["/usr/local/bin/node", "/universal/dist/src/server.js"]
